language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.3"

before_install:
    # Install conda
    - sudo pip install conda
    # install deps
    - sudo conda init
    - sudo conda update conda --yes
    - deps='pip numpy scipy pandas requests nose numpydoc matplotlib sphinx'
    - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
    - export PATH=$HOME/py/bin:$PATH
    - sudo apt-get install libsamplerate0 libsamplerate0-dev
    - pip install -r requirements.txt

install:
    # install your own package into the environment
    - python setup.py install

script:
    - "nosetests -w tests/ -v"
