language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.3"

before_install:
    - sudo apt-get update
    - sudo apt-get install python-numpy python-scipy cython
    - sudo apt-get install libatlas-dev liblapack-dev gfortran
    - sudo apt-get install libsamplerate0 libsamplerate0-dev
    - sudo apt-get install cython
    - pip install --upgrade -r requirements.txt
    - pip install pytest

install:
    - python setup.py install

script:
    - (cd tests && py.test test*.py)
