cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

jobs:
    include:
        - python: 3.6
          os: linux
          dist: bionic
        - python: 3.7
          os: linux
          dist: bionic
        - os: osx
          language: generic
          osx_image: xcode11

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda-$TRAVIS_OS_NAME$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment
    - conda list

install:
    # install your own package into the environment
    # pip install -e rather than setup.py, so that coverage can find the source
    - pip install --pre -e .[tests]

script:
    - python --version
    - pytest 

after_success:
    - coveralls
    - pip uninstall -y librosa

after_failure:
    - pip uninstall -y librosa
