language: python

python:
    - "2.7"
    - "3.3"

before_install:
    - sudo apt-get update
    - sudo apt-get install python-numpy python-scipy cython libatlas-dev liblapack-dev gfortran ffmpeg libsamplerate0
    - pip install -r requirements.txt
    - pip install pytest

install:
    - python setup.py install

script:
    - (cd tests && nosetests test*.py)
