language: python

python:
    - "2.7"

before_install:
    - sudo apt-get install liblapack-dev gfortran
    - pip install -r requirements.txt
    - pip install pytest

install:
    - python setup.py install

script:
    - py.test tests/test*.py
