name: CI

on: [push, pull_request]

jobs:
    test:
        name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-16.04
                      python-version: 3.7

                    - os: ubuntu-latest
                      python-version: 3.8

                    - os: ubuntu-latest
                      python-version: 3.9

                    - os: macos-latest
                      python-version: 3.8

                    - os: windows-latest
                      python-version: 3.8

        steps:
        - uses: actions/checkout@v2

        - name: Install OS dependencies
          run: |
              case "${{ runner.os }}" in
              Linux)
                sudo apt-get update -yy
                sudo apt-get install -yy  libsamplerate0 libsndfile1
                ;; 
              macOS)
                brew install libsamplerate
                ;;
              esac

        #- name: Cache conda
        # uses: actions/cache@v2
        # env:
        #   # Increase this value to reset cache if etc/example-environment.yml has not changed
        #   CACHE_NUMBER: 0
        # with:
        #   path: ~/conda_pkgs_dir
        #   key:
        #     ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
        #     hashFiles('etc/example-environment.yml') }}

        - name: Install Conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            channel-priority: strict
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

        - name: Install conda dependencies
          run: |
            conda install pip numpy scipy coverage scikit-learn!=0.19.0 matplotlib numba
            conda install -c conda-forge ffmpeg libsndfile pysoundfile coveralls

        - name: Conda info
          run: |
            conda info -a
            conda list

        - name: Install librosa
          run: python -m pip install --upgrade-strategy only-if-needed -e .[tests]

        - name: Run pytest
          run: pytest
