name: CI

on: [push, pull_request]

jobs:
    test:
        name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-16.04
                      python-version: 3.7

                    - os: ubuntu-latest
                      python-version: 3.8

                    - os: ubuntu-latest
                      python-version: 3.9

                    - os: macos-latest
                      python-version: 3.8

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
        - name: Install OS dependencies
          run: |
              case "${{ runner.os }}" in
              Linux)
                sudo apt-get update -yy
                sudo apt-get install -yy  libsamplerate0 libsndfile1
                ;; 
              macOS)
                brew install libsamplerate
                ;;
              esac

        - name: Cache conda
          uses: actions/cache@v2
          env:
            # Increase this value to reset cache if etc/example-environment.yml has not changed
            CACHE_NUMBER: 0
          with:
            path: ~/conda_pkgs_dir
            key:
              ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
              hashFiles('etc/example-environment.yml') }}

        - name: Install Conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            activate-environment: anaconda-client-env
            channel-priority: strict
            environment-file: etc/example-environment-caching.yml
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

        - name: Conda info
          shell: bash -l {0}
          run: conda info -a

        - name: Conda list
          shell: bash -l {0}
          run: conda list


        - name: Install librosa
          run: python -m pip install --pre -e .[tests]

        - name: Run pytest
          run: pytest
